src/Controllers/Version4/Utilities/DatabaseInformation.php
The WooCommerce REST API relies on the constant DB_NAME to display information about the database tables in the system status page. The problem is that this constant is not always defined (e.g., when the plugin HyperDB is used to replace the standard wpdb class). When that is the case, WooCommerce will incorrectly say that its core tables are missing and the following PHP warning will be generated:
```
Use of undefined constant DB_NAME - assumed 'DB_NAME' (this will throw an Error in a future version of PHP)
wp-content/plugins/woocommerce/includes/api/v2/class-wc-rest-system-status-v2-controller.php:708
```
To fix this, this commit checks to see if DB_NAME is defined before using it. When the constant is not set, WooCommerce will not try to get information about the tables. …
=> Fix: check if DB_NAME is defined before using it

unit-tests/Tests/Version2/settings.php, unit-tests/Tests/Version3/functions.php, unit-tests/Tests/Version3/settings.php, unit-tests/Tests/Version4/Settings.php
See https://github.com/woocommerce/woocommerce/pull/24207
=> Use WP_UnitTestCase::assertWPError() instead of WC_Unit_Test_Case::assertIsWPError()

src/Controllers/Version3/class-wc-rest-crud-controller.php, src/Controllers/Version4/AbstractObjectsController.php
Fixes #13 by filtering out empty/falsey objects before returning them for the loop.
=> filter empty objects from results before loop

src/Controllers/Version2/class-wc-rest-system-status-v2-controller.php, unit-tests/Tests/Version2/system-status.php, unit-tests/Tests/Version3/system-status.php
For some reason this got removed from the version 2 and 3 of our REST API.
=> Reintroduced "post_type_counts" in System Status

src/Controllers/Version1/class-wc-rest-products-v1-controller.php, src/Controllers/Version3/class-wc-rest-products-controller.php
I know changes in an API generally not desired, but this only affects values in the schema.
And the behaviour was already correct.
Fix Issue #76
=> Fix Products Controller images property type

src/Controllers/Version1/class-wc-rest-orders-v1-controller.php, src/Controllers/Version2/class-wc-rest-orders-v2-controller.php, unit-tests/Tests/Version2/orders.php, unit-tests/Tests/Version3/orders.php
While updating a `line_item` we only need an ID if we don't want to update the product data.
Closes  #61
=> Make product_id non mandatory while updating a line_item in orders endpoint

src/Controllers/Version2/class-wc-rest-products-v2-controller.php, unit-tests/Tests/Version2/product-variations.php, unit-tests/Tests/Version3/product-variations.php
This will add `orderby=menu_order` support to the products v2/v3 and product variation endpoints.
Closes #81.
=> Added support for filtering products and variations by their menu_order

src/Controllers/Version4/Requests/OrderRequest.php, unit-tests/Tests/Version4/Orders.php
Introduce the same fixes that we already merged for other endpoints in #79
=> [v4] Make product_id non mandatory while updating a line_item in orders endpoint

src/Controllers/Version4/Products.php, unit-tests/Tests/Version4/ProductVariations.php, unit-tests/Tests/Version4/Products.php
This adds the same support from #82 to the v4 endpoints.
=> Added menu_order ordering to the v4 product/variation endpoints

unit-tests/Tests/Version2/product-variations.php, unit-tests/Tests/Version2/products.php, unit-tests/Tests/Version3/product-variations.php, unit-tests/Tests/Version3/products.php, unit-tests/Tests/Version4/ProductVariations.php, unit-tests/Tests/Version4/Products.php, unit-tests/bin/install.sh
This PR fixes a problem in the script that configures the environment to run the unit tests in the Travis build jobs. The script was not running `composer install` in the WooCommerce directory, leaving it installation incomplete and thus the tests were failing.
To fix this problem, this PR adds a call to `composer install` right after WooCommerce is downloaded in the setup script (`unit-tests/bin/install.sh`).
After the changes described above, when the Travis build started running the tests again, a failign test was revealed. This test was fixed in commit d789631.
=> Fix unit test suite in the Travis build jobs

src/Controllers/Version2/class-wc-rest-system-status-v2-controller.php, src/Controllers/Version4/SystemStatus.php, src/Controllers/Version4/Utilities/DatabaseInformation.php, unit-tests/Tests/Version2/system-status.php, unit-tests/Tests/Version3/system-status.php, unit-tests/Tests/Version4/SystemStatus.php
`WC_Geolocation::get_local_database_path()` will get deprecated by https://github.com/woocommerce/woocommerce/pull/25378
So we need to deprecate it on v2 and v3, for v4 I'm removing this code.
=> Removed MaxMind from System Status

src/Controllers/Version2/class-wc-rest-shipping-zones-v2-controller.php
This commit fix `Error: No route was found matching the URL and request method {"status":404}` error.
=> Fixed wrong route path for shipping zone api

unit-tests/Tests/Version2/shipping-zones.php, unit-tests/Tests/Version3/shipping-zones.php
This PR updates two unit tests that were failing
(https://travis-ci.org/woocommerce/woocommerce-rest-api/jobs/637678251#L707),
after the behavior of the method
WC_REST_Shipping_Zones_V2_Controller::register_routes() changed in PR #104.
=> Fix unit tests to match new tested method behavior

src/Controllers/Version3/class-wc-rest-product-variations-controller.php, src/Controllers/Version3/class-wc-rest-products-controller.php, src/Controllers/Version4/ProductVariations.php, src/Controllers/Version4/Products.php
Reverts woocommerce/woocommerce-rest-api#84
Closes #111
**Test instructions:**
1. Create a product with regular price, sale price, weight and dimensions (by REST API or on the admin interface)
2. Try edit your product created on step on by the REST API, those values to an empty string, or null, or something else in an attempt to clean those values, since not all products are required to have sale price, weight or dimensions, check that nothing works to set empty those data.
3. Apply this patch and try edit by the REST API again, and check that now it's possible to clean out those values.
=> Revert "Fixed type numeric type on products and variations schema"

.gitattributes
The jetpack-autoloader used by WooCommerce requires version information in order to ensure the latest files are loaded. A consequence of this is that zip files generated from `master` appear usable but aren't. Running `composer install` against this package will result in a default version of `1.0.0.0`, which is less than it should be, and thus not used.
This PR sets all of the build files to `export-ignore` so they are not included in the package. This does make the package unusable unless cloned, but as it stands, it already is (it just doesn't tell you).
=> Added files that should be ignored on export to .gitattributes

src/Controllers/Version4/Utilities/BatchTrait.php
In BatchTrait, the access modifier of `get_public_batch_schema` is protected, however this trait is used by `AbstractController` which inherits from `WP_REST_Controller`. The class `WP_REST_Controller` also has a method called `get_public_batch_schema`, this causes access modifier conflict and generate warnings in console if you this class is loaded. 
This PR makes the access modifiers consistent with each other.
=> Change access modifier of get_public_batch_schema

phpcs.xml, src/Controllers/Version4/AbstractObjectsController.php, src/Controllers/Version4/Orders.php, src/Controllers/Version4/Products.php, src/Controllers/Version4/Responses/AbstractObjectResponse.php, src/Controllers/Version4/Responses/OrderResponse.php, src/Controllers/Version4/Responses/ProductResponse.php, src/Controllers/Version4/Responses/ProductVariationResponse.php, src/Controllers/Version4/Utilities/BatchTrait.php
This PR aims to improve the performance of API calls when not all fields are requested. Note that we can request selected fields by using the `_fields` parameter.
We improve the performance in two steps:
1. Eager load all the objects using a `get_post` query. This helps us by not having a separate query for every object in a loop. Note that we can do this only for objects which support casting a post object into their type, ideally without making any additional DB query. In this PR, this is only enabled for orders and products for now.
2. In our data structure, most of the data is available in `post` and `postmeta` objects, however, to fetch some data, we need to make additional queries to DB. Earlier we were doing these additional queries every time. Given, we may not need this data in …
=> Improve performance of API calls via eager loading and selecting high load fields only when requested

package.json, src/Controllers/Version2/class-wc-rest-products-v2-controller.php, src/Package.php, unit-tests/Bootstrap.php, unit-tests/Tests/Version2/shipping-zones.php, unit-tests/Tests/Version3/functions.php, unit-tests/Tests/Version3/products.php, unit-tests/Tests/Version3/shipping-zones.php, woocommerce-rest-api.php
This PR contains:
1. https://github.com/woocommerce/woocommerce-rest-api/pull/184
2. https://github.com/woocommerce/woocommerce-rest-api/pull/105
3. Commit for version bump and min PHP update.
=> Release 1.0.8 prep

src/Controllers/Version2/class-wc-rest-system-status-tools-v2-controller.php
Note this needs https://github.com/woocommerce/woocommerce/pull/26752 merged to work.
Use testing instructions from https://github.com/woocommerce/woocommerce/pull/26752.
Test failures are not related to this PR.
=> add clear template cache tool

src/Controllers/Version2/class-wc-rest-system-status-tools-v2-controller.php
Currently when Clear Transients action is performed via System Tools, the Action Scheduler Transients are not cleared resulting in incorrect comment counts.
Also Fixes https://github.com/woocommerce/woocommerce/issues/25750
=> Clear Action Scheduler Transients

src/Controllers/Version1/class-wc-rest-product-attributes-v1-controller.php, src/Controllers/Version4/ProductAttributes.php
Due to product attributes being retrieved from the object cache, there is no support for pagination, and therefore (I assume) no `X-WP-Total` and `X-WP-TotalPages` headers in the response.
We have a third-party app using the REST API and it expects and uses those headers to determine how many pages and/or results to expect and fetch.
=> add X-WP-Total headers to product attribute API calls

src/Controllers/Version1/class-wc-rest-coupons-v1-controller.php, src/Controllers/Version2/class-wc-rest-coupons-v2-controller.php
The expiry date for all API versions had a `string` type but should have `date-time`.
This only affects the schema, the behaviour was already correct.
Thanks
=> Fix expiry date fields in coupon schema definitions

src/Controllers/Version3/class-wc-rest-customers-controller.php, unit-tests/Tests/Version3/orders.php
Follow up from #54 to include tests and some fixes. Note that the documentation updates will still be required.
=> Support `modified` param for `orderby` in post based resources.

src/Controllers/Version2/class-wc-rest-coupons-v2-controller.php, src/Controllers/Version2/class-wc-rest-customers-v2-controller.php, src/Controllers/Version2/class-wc-rest-order-refunds-v2-controller.php, src/Controllers/Version2/class-wc-rest-orders-v2-controller.php, src/Controllers/Version2/class-wc-rest-product-variations-v2-controller.php, src/Controllers/Version2/class-wc-rest-products-v2-controller.php, src/Controllers/Version2/class-wc-rest-setting-options-v2-controller.php, src/Controllers/Version3/class-wc-rest-controller.php, src/Controllers/Version3/class-wc-rest-crud-controller.php, src/Controllers/Version3/class-wc-rest-customers-controller.php, src/Controllers/Version3/class-wc-rest-product-variations-controller.php, src/Controllers/Version3/class-wc-rest-products-controller.php, src/Controllers/Version3/class-wc-rest-setting-options-controller.php
This PR has a couple of changes in response to https://core.trac.wordpress.org/changeset/48306
1. Type `mixed` is now changed to appropriate scalar type with addition of `null`. So final type is now `array( {scalar}, 'null' )`. 
2. [High Impact] For settings API, the allowed type is now changed to `array`, `string`, `null`, and if an array, then allowed item type is `string` or `null`. This means that only one of nesting is now allowed for WooCommerce settings via API. Would appreciate the feedback here on if this is backward compatible or not. Looks like we have to mandatorily define the child properties if the native property is array or object. This means that just saying that type is `object` is not allowed, we have to define all the properties of children (and their children, etc if …
=> Fix compatibility for WP 5.5
